ALTER TABLE Teams
ADD CONSTRAINT coachToPFK FOREIGN KEY (coachID) REFERENCES Persons (personID)ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE GamePlayers 
ADD CONSTRAINT gameIDFK FOREIGN KEY (gameID) REFERENCES Games (gameID) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE GamePlayers 
ADD CONSTRAINT playerFK FOREIGN KEY (playerID) REFERENCES Players (playerID) ON DELETE RESTRICT;

